#include <iostream>

// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

int sumEvenTo(const int &n) {
    int a = 1, b = 2, c, s = 2;

    while (c < n) {
        c = a + b;
        a = b;
        b = c;

        if (c % 2 == 0) s += c;
    }

    return s;
}

int main() {
    std::cout << "Sum of the even-valued terms is " << sumEvenTo(4000000);

    return 0;
}
